package llvm;
import com.ochafik.lang.jnaerator.runtime.LibraryExtractor;
import com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper;
import com.ochafik.lang.jnaerator.runtime.NativeSize;
import com.ochafik.lang.jnaerator.runtime.NativeSizeByReference;
import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;
/**
 * JNA Wrapper for library <b>llvm-3.4</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface Llvm34Library extends Library {
	public static final String JNA_LIBRARY_NAME = LibraryExtractor.getLibraryPath("llvm-3.4", true, Llvm34Library.class);
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(Llvm34Library.JNA_LIBRARY_NAME, MangledFunctionMapper.DEFAULT_OPTIONS);
	public static final Llvm34Library INSTANCE = (Llvm34Library)Native.loadLibrary(Llvm34Library.JNA_LIBRARY_NAME, Llvm34Library.class, MangledFunctionMapper.DEFAULT_OPTIONS);
	public static interface LLVMVerifierFailureAction {
		public static final int LLVMAbortProcessAction = 0;
		public static final int LLVMPrintMessageAction = 1;
		public static final int LLVMReturnStatusAction = 2;
	};
	public static interface llvm_lto_status {
		public static final int LLVM_LTO_UNKNOWN = 0;
		public static final int LLVM_LTO_OPT_SUCCESS = 1;
		public static final int LLVM_LTO_READ_SUCCESS = 2;
		public static final int LLVM_LTO_READ_FAILURE = 3;
		public static final int LLVM_LTO_WRITE_FAILURE = 4;
		public static final int LLVM_LTO_NO_TARGET = 5;
		public static final int LLVM_LTO_NO_WORK = 6;
		public static final int LLVM_LTO_MODULE_MERGE_FAILURE = 7;
		public static final int LLVM_LTO_ASM_FAILURE = 8;
		public static final int LLVM_LTO_NULL_OBJECT = 9;
	};
	public static interface LLVMCodeGenOptLevel {
		public static final int LLVMCodeGenLevelNone = 0;
		public static final int LLVMCodeGenLevelLess = 1;
		public static final int LLVMCodeGenLevelDefault = 2;
		public static final int LLVMCodeGenLevelAggressive = 3;
	};
	public static interface LLVMRelocMode {
		public static final int LLVMRelocDefault = 0;
		public static final int LLVMRelocStatic = 1;
		public static final int LLVMRelocPIC = 2;
		public static final int LLVMRelocDynamicNoPic = 3;
	};
	public static interface LLVMCodeModel {
		public static final int LLVMCodeModelDefault = 0;
		public static final int LLVMCodeModelJITDefault = 1;
		public static final int LLVMCodeModelSmall = 2;
		public static final int LLVMCodeModelKernel = 3;
		public static final int LLVMCodeModelMedium = 4;
		public static final int LLVMCodeModelLarge = 5;
	};
	public static interface LLVMCodeGenFileType {
		public static final int LLVMAssemblyFile = 0;
		public static final int LLVMObjectFile = 1;
	};
	public static interface LLVMLinkerMode {
		public static final int LLVMLinkerDestroySource = 0;
		public static final int LLVMLinkerPreserveSource = 1;
	};
	public static interface LLVMByteOrdering {
		public static final int LLVMBigEndian = 0;
		public static final int LLVMLittleEndian = 1;
	};
	public static interface LLVMAttribute {
		public static final int LLVMZExtAttribute = 1 << 0;
		public static final int LLVMSExtAttribute = 1 << 1;
		public static final int LLVMNoReturnAttribute = 1 << 2;
		public static final int LLVMInRegAttribute = 1 << 3;
		public static final int LLVMStructRetAttribute = 1 << 4;
		public static final int LLVMNoUnwindAttribute = 1 << 5;
		public static final int LLVMNoAliasAttribute = 1 << 6;
		public static final int LLVMByValAttribute = 1 << 7;
		public static final int LLVMNestAttribute = 1 << 8;
		public static final int LLVMReadNoneAttribute = 1 << 9;
		public static final int LLVMReadOnlyAttribute = 1 << 10;
		public static final int LLVMNoInlineAttribute = 1 << 11;
		public static final int LLVMAlwaysInlineAttribute = 1 << 12;
		public static final int LLVMOptimizeForSizeAttribute = 1 << 13;
		public static final int LLVMStackProtectAttribute = 1 << 14;
		public static final int LLVMStackProtectReqAttribute = 1 << 15;
		public static final int LLVMAlignment = 31 << 16;
		public static final int LLVMNoCaptureAttribute = 1 << 21;
		public static final int LLVMNoRedZoneAttribute = 1 << 22;
		public static final int LLVMNoImplicitFloatAttribute = 1 << 23;
		public static final int LLVMNakedAttribute = 1 << 24;
		public static final int LLVMInlineHintAttribute = 1 << 25;
		public static final int LLVMStackAlignment = 7 << 26;
		public static final int LLVMReturnsTwice = 1 << 29;
		public static final int LLVMUWTable = 1 << 30;
		public static final int LLVMNonLazyBind = 1 << 31;
	};
	public static interface LLVMOpcode {
		public static final int LLVMRet = 1;
		public static final int LLVMBr = 2;
		public static final int LLVMSwitch = 3;
		public static final int LLVMIndirectBr = 4;
		public static final int LLVMInvoke = 5;
		public static final int LLVMUnreachable = 7;
		public static final int LLVMAdd = 8;
		public static final int LLVMFAdd = 9;
		public static final int LLVMSub = 10;
		public static final int LLVMFSub = 11;
		public static final int LLVMMul = 12;
		public static final int LLVMFMul = 13;
		public static final int LLVMUDiv = 14;
		public static final int LLVMSDiv = 15;
		public static final int LLVMFDiv = 16;
		public static final int LLVMURem = 17;
		public static final int LLVMSRem = 18;
		public static final int LLVMFRem = 19;
		public static final int LLVMShl = 20;
		public static final int LLVMLShr = 21;
		public static final int LLVMAShr = 22;
		public static final int LLVMAnd = 23;
		public static final int LLVMOr = 24;
		public static final int LLVMXor = 25;
		public static final int LLVMAlloca = 26;
		public static final int LLVMLoad = 27;
		public static final int LLVMStore = 28;
		public static final int LLVMGetElementPtr = 29;
		public static final int LLVMTrunc = 30;
		public static final int LLVMZExt = 31;
		public static final int LLVMSExt = 32;
		public static final int LLVMFPToUI = 33;
		public static final int LLVMFPToSI = 34;
		public static final int LLVMUIToFP = 35;
		public static final int LLVMSIToFP = 36;
		public static final int LLVMFPTrunc = 37;
		public static final int LLVMFPExt = 38;
		public static final int LLVMPtrToInt = 39;
		public static final int LLVMIntToPtr = 40;
		public static final int LLVMBitCast = 41;
		public static final int LLVMAddrSpaceCast = 60;
		public static final int LLVMICmp = 42;
		public static final int LLVMFCmp = 43;
		public static final int LLVMPHI = 44;
		public static final int LLVMCall = 45;
		public static final int LLVMSelect = 46;
		public static final int LLVMUserOp1 = 47;
		public static final int LLVMUserOp2 = 48;
		public static final int LLVMVAArg = 49;
		public static final int LLVMExtractElement = 50;
		public static final int LLVMInsertElement = 51;
		public static final int LLVMShuffleVector = 52;
		public static final int LLVMExtractValue = 53;
		public static final int LLVMInsertValue = 54;
		public static final int LLVMFence = 55;
		public static final int LLVMAtomicCmpXchg = 56;
		public static final int LLVMAtomicRMW = 57;
		public static final int LLVMResume = 58;
		public static final int LLVMLandingPad = 59;
	};
	public static interface LLVMTypeKind {
		public static final int LLVMVoidTypeKind = 0;
		public static final int LLVMHalfTypeKind = 1;
		public static final int LLVMFloatTypeKind = 2;
		public static final int LLVMDoubleTypeKind = 3;
		public static final int LLVMX86_FP80TypeKind = 4;
		public static final int LLVMFP128TypeKind = 5;
		public static final int LLVMPPC_FP128TypeKind = 6;
		public static final int LLVMLabelTypeKind = 7;
		public static final int LLVMIntegerTypeKind = 8;
		public static final int LLVMFunctionTypeKind = 9;
		public static final int LLVMStructTypeKind = 10;
		public static final int LLVMArrayTypeKind = 11;
		public static final int LLVMPointerTypeKind = 12;
		public static final int LLVMVectorTypeKind = 13;
		public static final int LLVMMetadataTypeKind = 14;
		public static final int LLVMX86_MMXTypeKind = 15;
	};
	public static interface LLVMLinkage {
		public static final int LLVMExternalLinkage = 0;
		public static final int LLVMAvailableExternallyLinkage = 1;
		public static final int LLVMLinkOnceAnyLinkage = 2;
		public static final int LLVMLinkOnceODRLinkage = 3;
		public static final int LLVMLinkOnceODRAutoHideLinkage = 4;
		public static final int LLVMWeakAnyLinkage = 5;
		public static final int LLVMWeakODRLinkage = 6;
		public static final int LLVMAppendingLinkage = 7;
		public static final int LLVMInternalLinkage = 8;
		public static final int LLVMPrivateLinkage = 9;
		public static final int LLVMDLLImportLinkage = 10;
		public static final int LLVMDLLExportLinkage = 11;
		public static final int LLVMExternalWeakLinkage = 12;
		public static final int LLVMGhostLinkage = 13;
		public static final int LLVMCommonLinkage = 14;
		public static final int LLVMLinkerPrivateLinkage = 15;
		public static final int LLVMLinkerPrivateWeakLinkage = 16;
	};
	public static interface LLVMVisibility {
		public static final int LLVMDefaultVisibility = 0;
		public static final int LLVMHiddenVisibility = 1;
		public static final int LLVMProtectedVisibility = 2;
	};
	public static interface LLVMCallConv {
		public static final int LLVMCCallConv = 0;
		public static final int LLVMFastCallConv = 8;
		public static final int LLVMColdCallConv = 9;
		public static final int LLVMWebKitJSCallConv = 12;
		public static final int LLVMAnyRegCallConv = 13;
		public static final int LLVMX86StdcallCallConv = 64;
		public static final int LLVMX86FastcallCallConv = 65;
	};
	public static interface LLVMIntPredicate {
		public static final int LLVMIntEQ = 32;
		public static final int LLVMIntNE = 33;
		public static final int LLVMIntUGT = 34;
		public static final int LLVMIntUGE = 35;
		public static final int LLVMIntULT = 36;
		public static final int LLVMIntULE = 37;
		public static final int LLVMIntSGT = 38;
		public static final int LLVMIntSGE = 39;
		public static final int LLVMIntSLT = 40;
		public static final int LLVMIntSLE = 41;
	};
	public static interface LLVMRealPredicate {
		public static final int LLVMRealPredicateFalse = 0;
		public static final int LLVMRealOEQ = 1;
		public static final int LLVMRealOGT = 2;
		public static final int LLVMRealOGE = 3;
		public static final int LLVMRealOLT = 4;
		public static final int LLVMRealOLE = 5;
		public static final int LLVMRealONE = 6;
		public static final int LLVMRealORD = 7;
		public static final int LLVMRealUNO = 8;
		public static final int LLVMRealUEQ = 9;
		public static final int LLVMRealUGT = 10;
		public static final int LLVMRealUGE = 11;
		public static final int LLVMRealULT = 12;
		public static final int LLVMRealULE = 13;
		public static final int LLVMRealUNE = 14;
		public static final int LLVMRealPredicateTrue = 15;
	};
	public static interface LLVMLandingPadClauseTy {
		public static final int LLVMLandingPadCatch = 0;
		public static final int LLVMLandingPadFilter = 1;
	};
	public static interface LLVMThreadLocalMode {
		public static final int LLVMNotThreadLocal = 0;
		public static final int LLVMGeneralDynamicTLSModel = 1;
		public static final int LLVMLocalDynamicTLSModel = 2;
		public static final int LLVMInitialExecTLSModel = 3;
		public static final int LLVMLocalExecTLSModel = 4;
	};
	public static interface LLVMAtomicOrdering {
		public static final int LLVMAtomicOrderingNotAtomic = 0;
		public static final int LLVMAtomicOrderingUnordered = 1;
		public static final int LLVMAtomicOrderingMonotonic = 2;
		public static final int LLVMAtomicOrderingAcquire = 4;
		public static final int LLVMAtomicOrderingRelease = 5;
		public static final int LLVMAtomicOrderingAcquireRelease = 6;
		public static final int LLVMAtomicOrderingSequentiallyConsistent = 7;
	};
	public static interface LLVMAtomicRMWBinOp {
		public static final int LLVMAtomicRMWBinOpXchg = 0;
		public static final int LLVMAtomicRMWBinOpAdd = 1;
		public static final int LLVMAtomicRMWBinOpSub = 2;
		public static final int LLVMAtomicRMWBinOpAnd = 3;
		public static final int LLVMAtomicRMWBinOpNand = 4;
		public static final int LLVMAtomicRMWBinOpOr = 5;
		public static final int LLVMAtomicRMWBinOpXor = 6;
		public static final int LLVMAtomicRMWBinOpMax = 7;
		public static final int LLVMAtomicRMWBinOpMin = 8;
		public static final int LLVMAtomicRMWBinOpUMax = 9;
		public static final int LLVMAtomicRMWBinOpUMin = 10;
	};
	public static interface lto_symbol_attributes {
		public static final int LTO_SYMBOL_ALIGNMENT_MASK = 0x0000001F;
		public static final int LTO_SYMBOL_PERMISSIONS_MASK = 0x000000E0;
		public static final int LTO_SYMBOL_PERMISSIONS_CODE = 0x000000A0;
		public static final int LTO_SYMBOL_PERMISSIONS_DATA = 0x000000C0;
		public static final int LTO_SYMBOL_PERMISSIONS_RODATA = 0x00000080;
		public static final int LTO_SYMBOL_DEFINITION_MASK = 0x00000700;
		public static final int LTO_SYMBOL_DEFINITION_REGULAR = 0x00000100;
		public static final int LTO_SYMBOL_DEFINITION_TENTATIVE = 0x00000200;
		public static final int LTO_SYMBOL_DEFINITION_WEAK = 0x00000300;
		public static final int LTO_SYMBOL_DEFINITION_UNDEFINED = 0x00000400;
		public static final int LTO_SYMBOL_DEFINITION_WEAKUNDEF = 0x00000500;
		public static final int LTO_SYMBOL_SCOPE_MASK = 0x00003800;
		public static final int LTO_SYMBOL_SCOPE_INTERNAL = 0x00000800;
		public static final int LTO_SYMBOL_SCOPE_HIDDEN = 0x00001000;
		public static final int LTO_SYMBOL_SCOPE_PROTECTED = 0x00002000;
		public static final int LTO_SYMBOL_SCOPE_DEFAULT = 0x00001800;
		public static final int LTO_SYMBOL_SCOPE_DEFAULT_CAN_BE_HIDDEN = 0x00002800;
	};
	public static interface lto_debug_model {
		public static final int LTO_DEBUG_MODEL_NONE = 0;
		public static final int LTO_DEBUG_MODEL_DWARF = 1;
	};
	public static interface lto_codegen_model {
		public static final int LTO_CODEGEN_PIC_MODEL_STATIC = 0;
		public static final int LTO_CODEGEN_PIC_MODEL_DYNAMIC = 1;
		public static final int LTO_CODEGEN_PIC_MODEL_DYNAMIC_NO_PIC = 2;
	};
	public static final int LLVMDisassembler_Option_AsmPrinterVariant = (int)4;
	public static final int LLVMDisassembler_Option_PrintLatency = (int)16;
	public static final int LLVMDisassembler_ReferenceType_Out_Objc_Message = (int)5;
	public static final int LLVMDisassembler_Option_UseMarkup = (int)1;
	public static final int LLVMDisassembler_ReferenceType_Out_Objc_Class_Ref = (int)8;
	public static final int LLVMDisassembler_ReferenceType_Out_Objc_Selector_Ref = (int)7;
	public static final int LLVMDisassembler_Option_PrintImmHex = (int)2;
	public static final int LTO_API_VERSION = (int)5;
	public static final int LLVMDisassembler_ReferenceType_Out_Objc_CFString_Ref = (int)4;
	public static final int LLVMDisassembler_ReferenceType_Out_Objc_Message_Ref = (int)6;
	public static final int LLVMDisassembler_ReferenceType_InOut_None = (int)0;
	public static final int LLVMDisassembler_ReferenceType_Out_SymbolStub = (int)1;
	public static final int LLVMDisassembler_VariantKind_ARM_HI16 = (int)1;
	public static final int LLVMDisassembler_VariantKind_ARM_LO16 = (int)2;
	public static final int LLVMDisassembler_Option_SetInstrComments = (int)8;
	public static final int LLVMDisassembler_VariantKind_None = (int)0;
	public static final int LLVMDisassembler_ReferenceType_Out_LitPool_SymAddr = (int)2;
	public static final int LLVMDisassembler_ReferenceType_In_PCrel_Load = (int)2;
	public static final int LLVMDisassembler_ReferenceType_Out_LitPool_CstrAddr = (int)3;
	public static final int LLVMDisassembler_ReferenceType_In_Branch = (int)1;
	public interface LLVMFatalErrorHandler extends Callback {
		void apply(Pointer Reason);
	};
	public interface LLVMMemoryManagerAllocateCodeSectionCallback extends Callback {
		Pointer apply(Pointer Opaque, IntByReference Size, int Alignment, int SectionID, Pointer SectionName);
	};
	public interface LLVMMemoryManagerAllocateDataSectionCallback extends Callback {
		Pointer apply(Pointer Opaque, IntByReference Size, int Alignment, int SectionID, Pointer SectionName, int IsReadOnly);
	};
	public interface LLVMMemoryManagerFinalizeMemoryCallback extends Callback {
		int apply(Pointer Opaque, PointerByReference ErrMsg);
	};
	public interface LLVMMemoryManagerDestroyCallback extends Callback {
		void apply(Pointer Opaque);
	};
	public interface LLVMOpInfoCallback extends Callback {
		int apply(Pointer DisInfo, long PC, long Offset, long Size, int TagType, Pointer TagBuf);
	};
	public interface LLVMSymbolLookupCallback extends Callback {
		String apply(Pointer DisInfo, long ReferenceValue, LongByReference ReferenceType, long ReferencePC, PointerByReference ReferenceName);
	};
	void LLVMAddAggressiveDCEPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddCFGSimplificationPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddDeadStoreEliminationPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddGVNPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddIndVarSimplifyPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddInstructionCombiningPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddJumpThreadingPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddLICMPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddLoopDeletionPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddLoopIdiomPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddLoopRotatePass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddLoopRerollPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddLoopUnrollPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddLoopUnswitchPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddMemCpyOptPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddPartiallyInlineLibCallsPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddPromoteMemoryToRegisterPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddReassociatePass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddSCCPPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddScalarReplAggregatesPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddScalarReplAggregatesPassSSA(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddScalarReplAggregatesPassWithThreshold(Llvm34Library.LLVMPassManagerRef PM, int Threshold);
	void LLVMAddSimplifyLibCallsPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddTailCallEliminationPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddConstantPropagationPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddDemoteMemoryToRegisterPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddVerifierPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddCorrelatedValuePropagationPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddEarlyCSEPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddLowerExpectIntrinsicPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddTypeBasedAliasAnalysisPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddBasicAliasAnalysisPass(Llvm34Library.LLVMPassManagerRef PM);
	Llvm34Library.LLVMPassManagerBuilderRef LLVMPassManagerBuilderCreate();
	void LLVMPassManagerBuilderDispose(Llvm34Library.LLVMPassManagerBuilderRef PMB);
	void LLVMPassManagerBuilderSetOptLevel(Llvm34Library.LLVMPassManagerBuilderRef PMB, int OptLevel);
	void LLVMPassManagerBuilderSetSizeLevel(Llvm34Library.LLVMPassManagerBuilderRef PMB, int SizeLevel);
	void LLVMPassManagerBuilderSetDisableUnitAtATime(Llvm34Library.LLVMPassManagerBuilderRef PMB, int Value);
	void LLVMPassManagerBuilderSetDisableUnrollLoops(Llvm34Library.LLVMPassManagerBuilderRef PMB, int Value);
	void LLVMPassManagerBuilderSetDisableSimplifyLibCalls(Llvm34Library.LLVMPassManagerBuilderRef PMB, int Value);
	void LLVMPassManagerBuilderUseInlinerWithThreshold(Llvm34Library.LLVMPassManagerBuilderRef PMB, int Threshold);
	void LLVMPassManagerBuilderPopulateFunctionPassManager(Llvm34Library.LLVMPassManagerBuilderRef PMB, Llvm34Library.LLVMPassManagerRef PM);
	void LLVMPassManagerBuilderPopulateModulePassManager(Llvm34Library.LLVMPassManagerBuilderRef PMB, Llvm34Library.LLVMPassManagerRef PM);
	void LLVMPassManagerBuilderPopulateLTOPassManager(Llvm34Library.LLVMPassManagerBuilderRef PMB, Llvm34Library.LLVMPassManagerRef PM, int Internalize, int RunInliner);
	void LLVMAddBBVectorizePass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddLoopVectorizePass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddSLPVectorizePass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddArgumentPromotionPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddConstantMergePass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddDeadArgEliminationPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddFunctionAttrsPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddFunctionInliningPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddAlwaysInlinerPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddGlobalDCEPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddGlobalOptimizerPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddIPConstantPropagationPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddPruneEHPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddIPSCCPPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddInternalizePass(int AllButMain);
	void LLVMAddStripDeadPrototypesPass(Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddStripSymbolsPass(Llvm34Library.LLVMPassManagerRef PM);
	int LLVMVerifyModule(Llvm34Library.LLVMModuleRef M, int Action, PointerByReference OutMessage);
	int LLVMVerifyFunction(Llvm34Library.LLVMValueRef Fn, int Action);
	void LLVMViewFunctionCFG(Llvm34Library.LLVMValueRef Fn);
	void LLVMViewFunctionCFGOnly(Llvm34Library.LLVMValueRef Fn);
	Pointer llvm_create_optimizer();
	void llvm_destroy_optimizer(Pointer lto);
	int llvm_read_object_file(Pointer lto, String input_filename);
	int llvm_optimize_modules(Pointer lto, String output_filename);
	Llvm34Library.LLVMTargetRef LLVMGetFirstTarget();
	Llvm34Library.LLVMTargetRef LLVMGetNextTarget(Llvm34Library.LLVMTargetRef T);
	Llvm34Library.LLVMTargetRef LLVMGetTargetFromName(String Name);
	int LLVMGetTargetFromTriple(String Triple, PointerByReference T, PointerByReference ErrorMessage);
	int LLVMGetTargetFromTriple(Pointer Triple, PointerByReference T, PointerByReference ErrorMessage);
	String LLVMGetTargetName(Llvm34Library.LLVMTargetRef T);
	String LLVMGetTargetDescription(Llvm34Library.LLVMTargetRef T);
	int LLVMTargetHasJIT(Llvm34Library.LLVMTargetRef T);
	int LLVMTargetHasTargetMachine(Llvm34Library.LLVMTargetRef T);
	int LLVMTargetHasAsmBackend(Llvm34Library.LLVMTargetRef T);
	Llvm34Library.LLVMTargetMachineRef LLVMCreateTargetMachine(Llvm34Library.LLVMTargetRef T, String Triple, String CPU, String Features, int Level, int Reloc, int CodeModel);
	void LLVMDisposeTargetMachine(Llvm34Library.LLVMTargetMachineRef T);
	Llvm34Library.LLVMTargetRef LLVMGetTargetMachineTarget(Llvm34Library.LLVMTargetMachineRef T);
	Pointer LLVMGetTargetMachineTriple(Llvm34Library.LLVMTargetMachineRef T);
	Pointer LLVMGetTargetMachineCPU(Llvm34Library.LLVMTargetMachineRef T);
	Pointer LLVMGetTargetMachineFeatureString(Llvm34Library.LLVMTargetMachineRef T);
	Llvm34Library.LLVMTargetDataRef LLVMGetTargetMachineData(Llvm34Library.LLVMTargetMachineRef T);
	void LLVMSetTargetMachineAsmVerbosity(Llvm34Library.LLVMTargetMachineRef T, int VerboseAsm);
	int LLVMTargetMachineEmitToFile(Llvm34Library.LLVMTargetMachineRef T, Llvm34Library.LLVMModuleRef M, ByteBuffer Filename, int codegen, PointerByReference ErrorMessage);
	int LLVMTargetMachineEmitToMemoryBuffer(Llvm34Library.LLVMTargetMachineRef T, Llvm34Library.LLVMModuleRef M, int codegen, PointerByReference ErrorMessage, PointerByReference OutMemBuf);
	int LLVMTargetMachineEmitToMemoryBuffer(Pointer T, Pointer M, int codegen, PointerByReference ErrorMessage, PointerByReference OutMemBuf);
	Pointer LLVMGetDefaultTargetTriple();
	int LLVMLinkModules(Llvm34Library.LLVMModuleRef Dest, Llvm34Library.LLVMModuleRef Src, int Mode, PointerByReference OutMessage);
	Llvm34Library.LLVMTargetDataRef LLVMCreateTargetData(String StringRep);
	void LLVMAddTargetData(Llvm34Library.LLVMTargetDataRef TD, Llvm34Library.LLVMPassManagerRef PM);
	void LLVMAddTargetLibraryInfo(Llvm34Library.LLVMTargetLibraryInfoRef TLI, Llvm34Library.LLVMPassManagerRef PM);
	Pointer LLVMCopyStringRepOfTargetData(Llvm34Library.LLVMTargetDataRef TD);
	int LLVMByteOrder(Llvm34Library.LLVMTargetDataRef TD);
	int LLVMPointerSize(Llvm34Library.LLVMTargetDataRef TD);
	int LLVMPointerSizeForAS(Llvm34Library.LLVMTargetDataRef TD, int AS);
	Llvm34Library.LLVMTypeRef LLVMIntPtrType(Llvm34Library.LLVMTargetDataRef TD);
	Llvm34Library.LLVMTypeRef LLVMIntPtrTypeForAS(Llvm34Library.LLVMTargetDataRef TD, int AS);
	Llvm34Library.LLVMTypeRef LLVMIntPtrTypeInContext(Llvm34Library.LLVMContextRef C, Llvm34Library.LLVMTargetDataRef TD);
	Llvm34Library.LLVMTypeRef LLVMIntPtrTypeForASInContext(Llvm34Library.LLVMContextRef C, Llvm34Library.LLVMTargetDataRef TD, int AS);
	long LLVMSizeOfTypeInBits(Llvm34Library.LLVMTargetDataRef TD, Llvm34Library.LLVMTypeRef Ty);
	long LLVMStoreSizeOfType(Llvm34Library.LLVMTargetDataRef TD, Llvm34Library.LLVMTypeRef Ty);
	long LLVMABISizeOfType(Llvm34Library.LLVMTargetDataRef TD, Llvm34Library.LLVMTypeRef Ty);
	int LLVMABIAlignmentOfType(Llvm34Library.LLVMTargetDataRef TD, Llvm34Library.LLVMTypeRef Ty);
	int LLVMCallFrameAlignmentOfType(Llvm34Library.LLVMTargetDataRef TD, Llvm34Library.LLVMTypeRef Ty);
	int LLVMPreferredAlignmentOfType(Llvm34Library.LLVMTargetDataRef TD, Llvm34Library.LLVMTypeRef Ty);
	int LLVMPreferredAlignmentOfGlobal(Llvm34Library.LLVMTargetDataRef TD, Llvm34Library.LLVMValueRef GlobalVar);
	int LLVMElementAtOffset(Llvm34Library.LLVMTargetDataRef TD, Llvm34Library.LLVMTypeRef StructTy, long Offset);
	long LLVMOffsetOfElement(Llvm34Library.LLVMTargetDataRef TD, Llvm34Library.LLVMTypeRef StructTy, int Element);
	void LLVMDisposeTargetData(Llvm34Library.LLVMTargetDataRef TD);
	int LLVMWriteBitcodeToFile(Llvm34Library.LLVMModuleRef M, String Path);
	int LLVMWriteBitcodeToFD(Llvm34Library.LLVMModuleRef M, int FD, int ShouldClose, int Unbuffered);
	int LLVMWriteBitcodeToFileHandle(Llvm34Library.LLVMModuleRef M, int Handle);
	void LLVMInitializeCore(Llvm34Library.LLVMPassRegistryRef R);
	void LLVMShutdown();
	Pointer LLVMCreateMessage(String Message);
	void LLVMDisposeMessage(ByteBuffer Message);
	void LLVMInstallFatalErrorHandler(Llvm34Library.LLVMFatalErrorHandler Handler);
	void LLVMResetFatalErrorHandler();
	void LLVMEnablePrettyStackTrace();
	Llvm34Library.LLVMContextRef LLVMContextCreate();
	Llvm34Library.LLVMContextRef LLVMGetGlobalContext();
	void LLVMContextDispose(Llvm34Library.LLVMContextRef C);
	int LLVMGetMDKindIDInContext(Llvm34Library.LLVMContextRef C, String Name, int SLen);
	int LLVMGetMDKindID(String Name, int SLen);
	Llvm34Library.LLVMModuleRef LLVMModuleCreateWithName(String ModuleID);
	Llvm34Library.LLVMModuleRef LLVMModuleCreateWithNameInContext(String ModuleID, Llvm34Library.LLVMContextRef C);
	void LLVMDisposeModule(Llvm34Library.LLVMModuleRef M);
	String LLVMGetDataLayout(Llvm34Library.LLVMModuleRef M);
	void LLVMSetDataLayout(Llvm34Library.LLVMModuleRef M, String Triple);
	String LLVMGetTarget(Llvm34Library.LLVMModuleRef M);
	void LLVMSetTarget(Llvm34Library.LLVMModuleRef M, String Triple);
	void LLVMDumpModule(Llvm34Library.LLVMModuleRef M);
	int LLVMPrintModuleToFile(Llvm34Library.LLVMModuleRef M, String Filename, PointerByReference ErrorMessage);
	Pointer LLVMPrintModuleToString(Llvm34Library.LLVMModuleRef M);
	void LLVMSetModuleInlineAsm(Llvm34Library.LLVMModuleRef M, String Asm);
	Llvm34Library.LLVMContextRef LLVMGetModuleContext(Llvm34Library.LLVMModuleRef M);
	Llvm34Library.LLVMTypeRef LLVMGetTypeByName(Llvm34Library.LLVMModuleRef M, String Name);
	int LLVMGetNamedMetadataNumOperands(Llvm34Library.LLVMModuleRef M, String name);
	void LLVMGetNamedMetadataOperands(Llvm34Library.LLVMModuleRef M, String name, PointerByReference Dest);
	void LLVMGetNamedMetadataOperands(Pointer M, Pointer name, PointerByReference Dest);
	void LLVMAddNamedMetadataOperand(Llvm34Library.LLVMModuleRef M, String name, Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMAddFunction(Llvm34Library.LLVMModuleRef M, String Name, Llvm34Library.LLVMTypeRef FunctionTy);
	Llvm34Library.LLVMValueRef LLVMGetNamedFunction(Llvm34Library.LLVMModuleRef M, String Name);
	Llvm34Library.LLVMValueRef LLVMGetFirstFunction(Llvm34Library.LLVMModuleRef M);
	Llvm34Library.LLVMValueRef LLVMGetLastFunction(Llvm34Library.LLVMModuleRef M);
	Llvm34Library.LLVMValueRef LLVMGetNextFunction(Llvm34Library.LLVMValueRef Fn);
	Llvm34Library.LLVMValueRef LLVMGetPreviousFunction(Llvm34Library.LLVMValueRef Fn);
	int LLVMGetTypeKind(Llvm34Library.LLVMTypeRef Ty);
	int LLVMTypeIsSized(Llvm34Library.LLVMTypeRef Ty);
	Llvm34Library.LLVMContextRef LLVMGetTypeContext(Llvm34Library.LLVMTypeRef Ty);
	void LLVMDumpType(Llvm34Library.LLVMTypeRef Val);
	Pointer LLVMPrintTypeToString(Llvm34Library.LLVMTypeRef Val);
	Llvm34Library.LLVMTypeRef LLVMInt1TypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMInt8TypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMInt16TypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMInt32TypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMInt64TypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMIntTypeInContext(Llvm34Library.LLVMContextRef C, int NumBits);
	Llvm34Library.LLVMTypeRef LLVMInt1Type();
	Llvm34Library.LLVMTypeRef LLVMInt8Type();
	Llvm34Library.LLVMTypeRef LLVMInt16Type();
	Llvm34Library.LLVMTypeRef LLVMInt32Type();
	Llvm34Library.LLVMTypeRef LLVMInt64Type();
	Llvm34Library.LLVMTypeRef LLVMIntType(int NumBits);
	int LLVMGetIntTypeWidth(Llvm34Library.LLVMTypeRef IntegerTy);
	Llvm34Library.LLVMTypeRef LLVMHalfTypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMFloatTypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMDoubleTypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMX86FP80TypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMFP128TypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMPPCFP128TypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMHalfType();
	Llvm34Library.LLVMTypeRef LLVMFloatType();
	Llvm34Library.LLVMTypeRef LLVMDoubleType();
	Llvm34Library.LLVMTypeRef LLVMX86FP80Type();
	Llvm34Library.LLVMTypeRef LLVMFP128Type();
	Llvm34Library.LLVMTypeRef LLVMPPCFP128Type();
	Llvm34Library.LLVMTypeRef LLVMFunctionType(Llvm34Library.LLVMTypeRef ReturnType, PointerByReference ParamTypes, int ParamCount, int IsVarArg);
	Llvm34Library.LLVMTypeRef LLVMFunctionType(Pointer ReturnType, PointerByReference ParamTypes, int ParamCount, int IsVarArg);
	int LLVMIsFunctionVarArg(Llvm34Library.LLVMTypeRef FunctionTy);
	Llvm34Library.LLVMTypeRef LLVMGetReturnType(Llvm34Library.LLVMTypeRef FunctionTy);
	int LLVMCountParamTypes(Llvm34Library.LLVMTypeRef FunctionTy);
	void LLVMGetParamTypes(Llvm34Library.LLVMTypeRef FunctionTy, PointerByReference Dest);
	void LLVMGetParamTypes(Pointer FunctionTy, PointerByReference Dest);
	Llvm34Library.LLVMTypeRef LLVMStructTypeInContext(Llvm34Library.LLVMContextRef C, PointerByReference ElementTypes, int ElementCount, int Packed);
	Llvm34Library.LLVMTypeRef LLVMStructTypeInContext(Pointer C, PointerByReference ElementTypes, int ElementCount, int Packed);
	Llvm34Library.LLVMTypeRef LLVMStructType(PointerByReference ElementTypes, int ElementCount, int Packed);
	Llvm34Library.LLVMTypeRef LLVMStructCreateNamed(Llvm34Library.LLVMContextRef C, String Name);
	String LLVMGetStructName(Llvm34Library.LLVMTypeRef Ty);
	void LLVMStructSetBody(Llvm34Library.LLVMTypeRef StructTy, PointerByReference ElementTypes, int ElementCount, int Packed);
	void LLVMStructSetBody(Pointer StructTy, PointerByReference ElementTypes, int ElementCount, int Packed);
	int LLVMCountStructElementTypes(Llvm34Library.LLVMTypeRef StructTy);
	void LLVMGetStructElementTypes(Llvm34Library.LLVMTypeRef StructTy, PointerByReference Dest);
	void LLVMGetStructElementTypes(Pointer StructTy, PointerByReference Dest);
	int LLVMIsPackedStruct(Llvm34Library.LLVMTypeRef StructTy);
	int LLVMIsOpaqueStruct(Llvm34Library.LLVMTypeRef StructTy);
	Llvm34Library.LLVMTypeRef LLVMGetElementType(Llvm34Library.LLVMTypeRef Ty);
	Llvm34Library.LLVMTypeRef LLVMArrayType(Llvm34Library.LLVMTypeRef ElementType, int ElementCount);
	int LLVMGetArrayLength(Llvm34Library.LLVMTypeRef ArrayTy);
	Llvm34Library.LLVMTypeRef LLVMPointerType(Llvm34Library.LLVMTypeRef ElementType, int AddressSpace);
	int LLVMGetPointerAddressSpace(Llvm34Library.LLVMTypeRef PointerTy);
	Llvm34Library.LLVMTypeRef LLVMVectorType(Llvm34Library.LLVMTypeRef ElementType, int ElementCount);
	int LLVMGetVectorSize(Llvm34Library.LLVMTypeRef VectorTy);
	Llvm34Library.LLVMTypeRef LLVMVoidTypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMLabelTypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMX86MMXTypeInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMTypeRef LLVMVoidType();
	Llvm34Library.LLVMTypeRef LLVMLabelType();
	Llvm34Library.LLVMTypeRef LLVMX86MMXType();
	Llvm34Library.LLVMTypeRef LLVMTypeOf(Llvm34Library.LLVMValueRef Val);
	String LLVMGetValueName(Llvm34Library.LLVMValueRef Val);
	void LLVMSetValueName(Llvm34Library.LLVMValueRef Val, String Name);
	void LLVMDumpValue(Llvm34Library.LLVMValueRef Val);
	Pointer LLVMPrintValueToString(Llvm34Library.LLVMValueRef Val);
	void LLVMReplaceAllUsesWith(Llvm34Library.LLVMValueRef OldVal, Llvm34Library.LLVMValueRef NewVal);
	int LLVMIsConstant(Llvm34Library.LLVMValueRef Val);
	int LLVMIsUndef(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAArgument(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsABasicBlock(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAInlineAsm(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAMDNode(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAMDString(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAUser(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstant(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsABlockAddress(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstantAggregateZero(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstantArray(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstantDataSequential(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstantDataArray(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstantDataVector(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstantExpr(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstantFP(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstantInt(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstantPointerNull(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstantStruct(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAConstantVector(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAGlobalValue(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAFunction(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAGlobalAlias(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAGlobalVariable(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAUndefValue(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAInstruction(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsABinaryOperator(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsACallInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAIntrinsicInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsADbgInfoIntrinsic(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsADbgDeclareInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAMemIntrinsic(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAMemCpyInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAMemMoveInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAMemSetInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsACmpInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAFCmpInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAICmpInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAExtractElementInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAGetElementPtrInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAInsertElementInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAInsertValueInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsALandingPadInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAPHINode(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsASelectInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAShuffleVectorInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAStoreInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsATerminatorInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsABranchInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAIndirectBrInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAInvokeInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAReturnInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsASwitchInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAUnreachableInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAResumeInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAUnaryInstruction(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAAllocaInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsACastInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAAddrSpaceCastInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsABitCastInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAFPExtInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAFPToSIInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAFPToUIInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAFPTruncInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAIntToPtrInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAPtrToIntInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsASExtInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsASIToFPInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsATruncInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAUIToFPInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAZExtInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAExtractValueInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsALoadInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMIsAVAArgInst(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMUseRef LLVMGetFirstUse(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMUseRef LLVMGetNextUse(Llvm34Library.LLVMUseRef U);
	Llvm34Library.LLVMValueRef LLVMGetUser(Llvm34Library.LLVMUseRef U);
	Llvm34Library.LLVMValueRef LLVMGetUsedValue(Llvm34Library.LLVMUseRef U);
	Llvm34Library.LLVMValueRef LLVMGetOperand(Llvm34Library.LLVMValueRef Val, int Index);
	void LLVMSetOperand(Llvm34Library.LLVMValueRef User, int Index, Llvm34Library.LLVMValueRef Val);
	int LLVMGetNumOperands(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMConstNull(Llvm34Library.LLVMTypeRef Ty);
	Llvm34Library.LLVMValueRef LLVMConstAllOnes(Llvm34Library.LLVMTypeRef Ty);
	Llvm34Library.LLVMValueRef LLVMGetUndef(Llvm34Library.LLVMTypeRef Ty);
	int LLVMIsNull(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMConstPointerNull(Llvm34Library.LLVMTypeRef Ty);
	Llvm34Library.LLVMValueRef LLVMConstInt(Llvm34Library.LLVMTypeRef IntTy, long N, int SignExtend);
	Llvm34Library.LLVMValueRef LLVMConstIntOfArbitraryPrecision(Llvm34Library.LLVMTypeRef IntTy, int NumWords, long Words[]);
	Llvm34Library.LLVMValueRef LLVMConstIntOfString(Llvm34Library.LLVMTypeRef IntTy, String Text, byte Radix);
	Llvm34Library.LLVMValueRef LLVMConstIntOfStringAndSize(Llvm34Library.LLVMTypeRef IntTy, String Text, int SLen, byte Radix);
	Llvm34Library.LLVMValueRef LLVMConstReal(Llvm34Library.LLVMTypeRef RealTy, double N);
	Llvm34Library.LLVMValueRef LLVMConstRealOfString(Llvm34Library.LLVMTypeRef RealTy, String Text);
	Llvm34Library.LLVMValueRef LLVMConstRealOfStringAndSize(Llvm34Library.LLVMTypeRef RealTy, String Text, int SLen);
	long LLVMConstIntGetZExtValue(Llvm34Library.LLVMValueRef ConstantVal);
	long LLVMConstIntGetSExtValue(Llvm34Library.LLVMValueRef ConstantVal);
	Llvm34Library.LLVMValueRef LLVMConstStringInContext(Llvm34Library.LLVMContextRef C, String Str, int Length, int DontNullTerminate);
	Llvm34Library.LLVMValueRef LLVMConstString(String Str, int Length, int DontNullTerminate);
	Llvm34Library.LLVMValueRef LLVMConstStructInContext(Llvm34Library.LLVMContextRef C, PointerByReference ConstantVals, int Count, int Packed);
	Llvm34Library.LLVMValueRef LLVMConstStructInContext(Pointer C, PointerByReference ConstantVals, int Count, int Packed);
	Llvm34Library.LLVMValueRef LLVMConstStruct(PointerByReference ConstantVals, int Count, int Packed);
	Llvm34Library.LLVMValueRef LLVMConstArray(Llvm34Library.LLVMTypeRef ElementTy, PointerByReference ConstantVals, int Length);
	Llvm34Library.LLVMValueRef LLVMConstArray(Pointer ElementTy, PointerByReference ConstantVals, int Length);
	Llvm34Library.LLVMValueRef LLVMConstNamedStruct(Llvm34Library.LLVMTypeRef StructTy, PointerByReference ConstantVals, int Count);
	Llvm34Library.LLVMValueRef LLVMConstNamedStruct(Pointer StructTy, PointerByReference ConstantVals, int Count);
	Llvm34Library.LLVMValueRef LLVMConstVector(PointerByReference ScalarConstantVals, int Size);
	int LLVMGetConstOpcode(Llvm34Library.LLVMValueRef ConstantVal);
	Llvm34Library.LLVMValueRef LLVMAlignOf(Llvm34Library.LLVMTypeRef Ty);
	Llvm34Library.LLVMValueRef LLVMSizeOf(Llvm34Library.LLVMTypeRef Ty);
	Llvm34Library.LLVMValueRef LLVMConstNeg(Llvm34Library.LLVMValueRef ConstantVal);
	Llvm34Library.LLVMValueRef LLVMConstNSWNeg(Llvm34Library.LLVMValueRef ConstantVal);
	Llvm34Library.LLVMValueRef LLVMConstNUWNeg(Llvm34Library.LLVMValueRef ConstantVal);
	Llvm34Library.LLVMValueRef LLVMConstFNeg(Llvm34Library.LLVMValueRef ConstantVal);
	Llvm34Library.LLVMValueRef LLVMConstNot(Llvm34Library.LLVMValueRef ConstantVal);
	Llvm34Library.LLVMValueRef LLVMConstAdd(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstNSWAdd(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstNUWAdd(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstFAdd(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstSub(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstNSWSub(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstNUWSub(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstFSub(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstMul(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstNSWMul(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstNUWMul(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstFMul(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstUDiv(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstSDiv(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstExactSDiv(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstFDiv(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstURem(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstSRem(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstFRem(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstAnd(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstOr(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstXor(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstICmp(int Predicate, Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstFCmp(int Predicate, Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstShl(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstLShr(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstAShr(Llvm34Library.LLVMValueRef LHSConstant, Llvm34Library.LLVMValueRef RHSConstant);
	Llvm34Library.LLVMValueRef LLVMConstGEP(Llvm34Library.LLVMValueRef ConstantVal, PointerByReference ConstantIndices, int NumIndices);
	Llvm34Library.LLVMValueRef LLVMConstGEP(Pointer ConstantVal, PointerByReference ConstantIndices, int NumIndices);
	Llvm34Library.LLVMValueRef LLVMConstInBoundsGEP(Llvm34Library.LLVMValueRef ConstantVal, PointerByReference ConstantIndices, int NumIndices);
	Llvm34Library.LLVMValueRef LLVMConstInBoundsGEP(Pointer ConstantVal, PointerByReference ConstantIndices, int NumIndices);
	Llvm34Library.LLVMValueRef LLVMConstTrunc(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstSExt(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstZExt(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstFPTrunc(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstFPExt(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstUIToFP(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstSIToFP(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstFPToUI(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstFPToSI(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstPtrToInt(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstIntToPtr(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstBitCast(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstAddrSpaceCast(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstZExtOrBitCast(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstSExtOrBitCast(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstTruncOrBitCast(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstPointerCast(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstIntCast(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType, int isSigned);
	Llvm34Library.LLVMValueRef LLVMConstFPCast(Llvm34Library.LLVMValueRef ConstantVal, Llvm34Library.LLVMTypeRef ToType);
	Llvm34Library.LLVMValueRef LLVMConstSelect(Llvm34Library.LLVMValueRef ConstantCondition, Llvm34Library.LLVMValueRef ConstantIfTrue, Llvm34Library.LLVMValueRef ConstantIfFalse);
	Llvm34Library.LLVMValueRef LLVMConstExtractElement(Llvm34Library.LLVMValueRef VectorConstant, Llvm34Library.LLVMValueRef IndexConstant);
	Llvm34Library.LLVMValueRef LLVMConstInsertElement(Llvm34Library.LLVMValueRef VectorConstant, Llvm34Library.LLVMValueRef ElementValueConstant, Llvm34Library.LLVMValueRef IndexConstant);
	Llvm34Library.LLVMValueRef LLVMConstShuffleVector(Llvm34Library.LLVMValueRef VectorAConstant, Llvm34Library.LLVMValueRef VectorBConstant, Llvm34Library.LLVMValueRef MaskConstant);
	Llvm34Library.LLVMValueRef LLVMConstExtractValue(Llvm34Library.LLVMValueRef AggConstant, IntBuffer IdxList, int NumIdx);
	Llvm34Library.LLVMValueRef LLVMConstInsertValue(Llvm34Library.LLVMValueRef AggConstant, Llvm34Library.LLVMValueRef ElementValueConstant, IntBuffer IdxList, int NumIdx);
	Llvm34Library.LLVMValueRef LLVMConstInlineAsm(Llvm34Library.LLVMTypeRef Ty, String AsmString, String Constraints, int HasSideEffects, int IsAlignStack);
	Llvm34Library.LLVMValueRef LLVMBlockAddress(Llvm34Library.LLVMValueRef F, Llvm34Library.LLVMBasicBlockRef BB);
	Llvm34Library.LLVMModuleRef LLVMGetGlobalParent(Llvm34Library.LLVMValueRef Global);
	int LLVMIsDeclaration(Llvm34Library.LLVMValueRef Global);
	int LLVMGetLinkage(Llvm34Library.LLVMValueRef Global);
	void LLVMSetLinkage(Llvm34Library.LLVMValueRef Global, int Linkage);
	String LLVMGetSection(Llvm34Library.LLVMValueRef Global);
	void LLVMSetSection(Llvm34Library.LLVMValueRef Global, String Section);
	int LLVMGetVisibility(Llvm34Library.LLVMValueRef Global);
	void LLVMSetVisibility(Llvm34Library.LLVMValueRef Global, int Viz);
	int LLVMGetAlignment(Llvm34Library.LLVMValueRef V);
	void LLVMSetAlignment(Llvm34Library.LLVMValueRef V, int Bytes);
	Llvm34Library.LLVMValueRef LLVMAddGlobal(Llvm34Library.LLVMModuleRef M, Llvm34Library.LLVMTypeRef Ty, String Name);
	Llvm34Library.LLVMValueRef LLVMAddGlobalInAddressSpace(Llvm34Library.LLVMModuleRef M, Llvm34Library.LLVMTypeRef Ty, String Name, int AddressSpace);
	Llvm34Library.LLVMValueRef LLVMGetNamedGlobal(Llvm34Library.LLVMModuleRef M, String Name);
	Llvm34Library.LLVMValueRef LLVMGetFirstGlobal(Llvm34Library.LLVMModuleRef M);
	Llvm34Library.LLVMValueRef LLVMGetLastGlobal(Llvm34Library.LLVMModuleRef M);
	Llvm34Library.LLVMValueRef LLVMGetNextGlobal(Llvm34Library.LLVMValueRef GlobalVar);
	Llvm34Library.LLVMValueRef LLVMGetPreviousGlobal(Llvm34Library.LLVMValueRef GlobalVar);
	void LLVMDeleteGlobal(Llvm34Library.LLVMValueRef GlobalVar);
	Llvm34Library.LLVMValueRef LLVMGetInitializer(Llvm34Library.LLVMValueRef GlobalVar);
	void LLVMSetInitializer(Llvm34Library.LLVMValueRef GlobalVar, Llvm34Library.LLVMValueRef ConstantVal);
	int LLVMIsThreadLocal(Llvm34Library.LLVMValueRef GlobalVar);
	void LLVMSetThreadLocal(Llvm34Library.LLVMValueRef GlobalVar, int IsThreadLocal);
	int LLVMIsGlobalConstant(Llvm34Library.LLVMValueRef GlobalVar);
	void LLVMSetGlobalConstant(Llvm34Library.LLVMValueRef GlobalVar, int IsConstant);
	int LLVMGetThreadLocalMode(Llvm34Library.LLVMValueRef GlobalVar);
	void LLVMSetThreadLocalMode(Llvm34Library.LLVMValueRef GlobalVar, int Mode);
	int LLVMIsExternallyInitialized(Llvm34Library.LLVMValueRef GlobalVar);
	void LLVMSetExternallyInitialized(Llvm34Library.LLVMValueRef GlobalVar, int IsExtInit);
	Llvm34Library.LLVMValueRef LLVMAddAlias(Llvm34Library.LLVMModuleRef M, Llvm34Library.LLVMTypeRef Ty, Llvm34Library.LLVMValueRef Aliasee, String Name);
	void LLVMDeleteFunction(Llvm34Library.LLVMValueRef Fn);
	int LLVMGetIntrinsicID(Llvm34Library.LLVMValueRef Fn);
	int LLVMGetFunctionCallConv(Llvm34Library.LLVMValueRef Fn);
	void LLVMSetFunctionCallConv(Llvm34Library.LLVMValueRef Fn, int CC);
	String LLVMGetGC(Llvm34Library.LLVMValueRef Fn);
	void LLVMSetGC(Llvm34Library.LLVMValueRef Fn, String Name);
	void LLVMAddFunctionAttr(Llvm34Library.LLVMValueRef Fn, int PA);
	void LLVMAddTargetDependentFunctionAttr(Llvm34Library.LLVMValueRef Fn, String A, String V);
	int LLVMGetFunctionAttr(Llvm34Library.LLVMValueRef Fn);
	void LLVMRemoveFunctionAttr(Llvm34Library.LLVMValueRef Fn, int PA);
	int LLVMCountParams(Llvm34Library.LLVMValueRef Fn);
	void LLVMGetParams(Llvm34Library.LLVMValueRef Fn, PointerByReference Params);
	void LLVMGetParams(Pointer Fn, PointerByReference Params);
	Llvm34Library.LLVMValueRef LLVMGetParam(Llvm34Library.LLVMValueRef Fn, int Index);
	Llvm34Library.LLVMValueRef LLVMGetParamParent(Llvm34Library.LLVMValueRef Inst);
	Llvm34Library.LLVMValueRef LLVMGetFirstParam(Llvm34Library.LLVMValueRef Fn);
	Llvm34Library.LLVMValueRef LLVMGetLastParam(Llvm34Library.LLVMValueRef Fn);
	Llvm34Library.LLVMValueRef LLVMGetNextParam(Llvm34Library.LLVMValueRef Arg);
	Llvm34Library.LLVMValueRef LLVMGetPreviousParam(Llvm34Library.LLVMValueRef Arg);
	void LLVMAddAttribute(Llvm34Library.LLVMValueRef Arg, int PA);
	void LLVMRemoveAttribute(Llvm34Library.LLVMValueRef Arg, int PA);
	int LLVMGetAttribute(Llvm34Library.LLVMValueRef Arg);
	void LLVMSetParamAlignment(Llvm34Library.LLVMValueRef Arg, int align);
	Llvm34Library.LLVMValueRef LLVMMDStringInContext(Llvm34Library.LLVMContextRef C, String Str, int SLen);
	Llvm34Library.LLVMValueRef LLVMMDString(String Str, int SLen);
	Llvm34Library.LLVMValueRef LLVMMDNodeInContext(Llvm34Library.LLVMContextRef C, PointerByReference Vals, int Count);
	Llvm34Library.LLVMValueRef LLVMMDNodeInContext(Pointer C, PointerByReference Vals, int Count);
	Llvm34Library.LLVMValueRef LLVMMDNode(PointerByReference Vals, int Count);
	String LLVMGetMDString(Llvm34Library.LLVMValueRef V, IntBuffer Len);
	int LLVMGetMDNodeNumOperands(Llvm34Library.LLVMValueRef V);
	void LLVMGetMDNodeOperands(Llvm34Library.LLVMValueRef V, PointerByReference Dest);
	void LLVMGetMDNodeOperands(Pointer V, PointerByReference Dest);
	Llvm34Library.LLVMValueRef LLVMBasicBlockAsValue(Llvm34Library.LLVMBasicBlockRef BB);
	int LLVMValueIsBasicBlock(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMBasicBlockRef LLVMValueAsBasicBlock(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMGetBasicBlockParent(Llvm34Library.LLVMBasicBlockRef BB);
	Llvm34Library.LLVMValueRef LLVMGetBasicBlockTerminator(Llvm34Library.LLVMBasicBlockRef BB);
	int LLVMCountBasicBlocks(Llvm34Library.LLVMValueRef Fn);
	void LLVMGetBasicBlocks(Llvm34Library.LLVMValueRef Fn, PointerByReference BasicBlocks);
	void LLVMGetBasicBlocks(Pointer Fn, PointerByReference BasicBlocks);
	Llvm34Library.LLVMBasicBlockRef LLVMGetFirstBasicBlock(Llvm34Library.LLVMValueRef Fn);
	Llvm34Library.LLVMBasicBlockRef LLVMGetLastBasicBlock(Llvm34Library.LLVMValueRef Fn);
	Llvm34Library.LLVMBasicBlockRef LLVMGetNextBasicBlock(Llvm34Library.LLVMBasicBlockRef BB);
	Llvm34Library.LLVMBasicBlockRef LLVMGetPreviousBasicBlock(Llvm34Library.LLVMBasicBlockRef BB);
	Llvm34Library.LLVMBasicBlockRef LLVMGetEntryBasicBlock(Llvm34Library.LLVMValueRef Fn);
	Llvm34Library.LLVMBasicBlockRef LLVMAppendBasicBlockInContext(Llvm34Library.LLVMContextRef C, Llvm34Library.LLVMValueRef Fn, String Name);
	Llvm34Library.LLVMBasicBlockRef LLVMAppendBasicBlock(Llvm34Library.LLVMValueRef Fn, String Name);
	Llvm34Library.LLVMBasicBlockRef LLVMInsertBasicBlockInContext(Llvm34Library.LLVMContextRef C, Llvm34Library.LLVMBasicBlockRef BB, String Name);
	Llvm34Library.LLVMBasicBlockRef LLVMInsertBasicBlock(Llvm34Library.LLVMBasicBlockRef InsertBeforeBB, String Name);
	void LLVMDeleteBasicBlock(Llvm34Library.LLVMBasicBlockRef BB);
	void LLVMRemoveBasicBlockFromParent(Llvm34Library.LLVMBasicBlockRef BB);
	void LLVMMoveBasicBlockBefore(Llvm34Library.LLVMBasicBlockRef BB, Llvm34Library.LLVMBasicBlockRef MovePos);
	void LLVMMoveBasicBlockAfter(Llvm34Library.LLVMBasicBlockRef BB, Llvm34Library.LLVMBasicBlockRef MovePos);
	Llvm34Library.LLVMValueRef LLVMGetFirstInstruction(Llvm34Library.LLVMBasicBlockRef BB);
	Llvm34Library.LLVMValueRef LLVMGetLastInstruction(Llvm34Library.LLVMBasicBlockRef BB);
	int LLVMHasMetadata(Llvm34Library.LLVMValueRef Val);
	Llvm34Library.LLVMValueRef LLVMGetMetadata(Llvm34Library.LLVMValueRef Val, int KindID);
	void LLVMSetMetadata(Llvm34Library.LLVMValueRef Val, int KindID, Llvm34Library.LLVMValueRef Node);
	Llvm34Library.LLVMBasicBlockRef LLVMGetInstructionParent(Llvm34Library.LLVMValueRef Inst);
	Llvm34Library.LLVMValueRef LLVMGetNextInstruction(Llvm34Library.LLVMValueRef Inst);
	Llvm34Library.LLVMValueRef LLVMGetPreviousInstruction(Llvm34Library.LLVMValueRef Inst);
	void LLVMInstructionEraseFromParent(Llvm34Library.LLVMValueRef Inst);
	int LLVMGetInstructionOpcode(Llvm34Library.LLVMValueRef Inst);
	int LLVMGetICmpPredicate(Llvm34Library.LLVMValueRef Inst);
	void LLVMSetInstructionCallConv(Llvm34Library.LLVMValueRef Instr, int CC);
	int LLVMGetInstructionCallConv(Llvm34Library.LLVMValueRef Instr);
	void LLVMAddInstrAttribute(Llvm34Library.LLVMValueRef Instr, int index, int LLVMAttribute1);
	void LLVMRemoveInstrAttribute(Llvm34Library.LLVMValueRef Instr, int index, int LLVMAttribute1);
	void LLVMSetInstrParamAlignment(Llvm34Library.LLVMValueRef Instr, int index, int align);
	int LLVMIsTailCall(Llvm34Library.LLVMValueRef CallInst);
	void LLVMSetTailCall(Llvm34Library.LLVMValueRef CallInst, int IsTailCall);
	Llvm34Library.LLVMBasicBlockRef LLVMGetSwitchDefaultDest(Llvm34Library.LLVMValueRef SwitchInstr);
	void LLVMAddIncoming(Llvm34Library.LLVMValueRef PhiNode, PointerByReference IncomingValues, PointerByReference IncomingBlocks, int Count);
	void LLVMAddIncoming(Pointer PhiNode, PointerByReference IncomingValues, PointerByReference IncomingBlocks, int Count);
	int LLVMCountIncoming(Llvm34Library.LLVMValueRef PhiNode);
	Llvm34Library.LLVMValueRef LLVMGetIncomingValue(Llvm34Library.LLVMValueRef PhiNode, int Index);
	Llvm34Library.LLVMBasicBlockRef LLVMGetIncomingBlock(Llvm34Library.LLVMValueRef PhiNode, int Index);
	Llvm34Library.LLVMBuilderRef LLVMCreateBuilderInContext(Llvm34Library.LLVMContextRef C);
	Llvm34Library.LLVMBuilderRef LLVMCreateBuilder();
	void LLVMPositionBuilder(Llvm34Library.LLVMBuilderRef Builder, Llvm34Library.LLVMBasicBlockRef Block, Llvm34Library.LLVMValueRef Instr);
	void LLVMPositionBuilderBefore(Llvm34Library.LLVMBuilderRef Builder, Llvm34Library.LLVMValueRef Instr);
	void LLVMPositionBuilderAtEnd(Llvm34Library.LLVMBuilderRef Builder, Llvm34Library.LLVMBasicBlockRef Block);
	Llvm34Library.LLVMBasicBlockRef LLVMGetInsertBlock(Llvm34Library.LLVMBuilderRef Builder);
	void LLVMClearInsertionPosition(Llvm34Library.LLVMBuilderRef Builder);
	void LLVMInsertIntoBuilder(Llvm34Library.LLVMBuilderRef Builder, Llvm34Library.LLVMValueRef Instr);
	void LLVMInsertIntoBuilderWithName(Llvm34Library.LLVMBuilderRef Builder, Llvm34Library.LLVMValueRef Instr, String Name);
	void LLVMDisposeBuilder(Llvm34Library.LLVMBuilderRef Builder);
	void LLVMSetCurrentDebugLocation(Llvm34Library.LLVMBuilderRef Builder, Llvm34Library.LLVMValueRef L);
	Llvm34Library.LLVMValueRef LLVMGetCurrentDebugLocation(Llvm34Library.LLVMBuilderRef Builder);
	void LLVMSetInstDebugLocation(Llvm34Library.LLVMBuilderRef Builder, Llvm34Library.LLVMValueRef Inst);
	Llvm34Library.LLVMValueRef LLVMBuildRetVoid(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1);
	Llvm34Library.LLVMValueRef LLVMBuildRet(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef V);
	Llvm34Library.LLVMValueRef LLVMBuildAggregateRet(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, PointerByReference RetVals, int N);
	Llvm34Library.LLVMValueRef LLVMBuildAggregateRet(Pointer LLVMBuilderRef1, PointerByReference RetVals, int N);
	Llvm34Library.LLVMValueRef LLVMBuildBr(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMBasicBlockRef Dest);
	Llvm34Library.LLVMValueRef LLVMBuildCondBr(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef If, Llvm34Library.LLVMBasicBlockRef Then, Llvm34Library.LLVMBasicBlockRef Else);
	Llvm34Library.LLVMValueRef LLVMBuildSwitch(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef V, Llvm34Library.LLVMBasicBlockRef Else, int NumCases);
	Llvm34Library.LLVMValueRef LLVMBuildIndirectBr(Llvm34Library.LLVMBuilderRef B, Llvm34Library.LLVMValueRef Addr, int NumDests);
	Llvm34Library.LLVMValueRef LLVMBuildInvoke(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Fn, PointerByReference Args, int NumArgs, Llvm34Library.LLVMBasicBlockRef Then, Llvm34Library.LLVMBasicBlockRef Catch, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildInvoke(Pointer LLVMBuilderRef1, Pointer Fn, PointerByReference Args, int NumArgs, Pointer Then, Pointer Catch, Pointer Name);
	Llvm34Library.LLVMValueRef LLVMBuildLandingPad(Llvm34Library.LLVMBuilderRef B, Llvm34Library.LLVMTypeRef Ty, Llvm34Library.LLVMValueRef PersFn, int NumClauses, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildResume(Llvm34Library.LLVMBuilderRef B, Llvm34Library.LLVMValueRef Exn);
	Llvm34Library.LLVMValueRef LLVMBuildUnreachable(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1);
	void LLVMAddCase(Llvm34Library.LLVMValueRef Switch, Llvm34Library.LLVMValueRef OnVal, Llvm34Library.LLVMBasicBlockRef Dest);
	void LLVMAddDestination(Llvm34Library.LLVMValueRef IndirectBr, Llvm34Library.LLVMBasicBlockRef Dest);
	void LLVMAddClause(Llvm34Library.LLVMValueRef LandingPad, Llvm34Library.LLVMValueRef ClauseVal);
	void LLVMSetCleanup(Llvm34Library.LLVMValueRef LandingPad, int Val);
	Llvm34Library.LLVMValueRef LLVMBuildAdd(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildNSWAdd(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildNUWAdd(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFAdd(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildSub(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildNSWSub(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildNUWSub(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFSub(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildMul(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildNSWMul(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildNUWMul(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFMul(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildUDiv(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildSDiv(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildExactSDiv(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFDiv(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildURem(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildSRem(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFRem(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildShl(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildLShr(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildAShr(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildAnd(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildOr(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildXor(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildBinOp(Llvm34Library.LLVMBuilderRef B, int Op, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildNeg(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef V, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildNSWNeg(Llvm34Library.LLVMBuilderRef B, Llvm34Library.LLVMValueRef V, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildNUWNeg(Llvm34Library.LLVMBuilderRef B, Llvm34Library.LLVMValueRef V, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFNeg(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef V, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildNot(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef V, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildMalloc(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMTypeRef Ty, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildArrayMalloc(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMTypeRef Ty, Llvm34Library.LLVMValueRef Val, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildAlloca(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMTypeRef Ty, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildArrayAlloca(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMTypeRef Ty, Llvm34Library.LLVMValueRef Val, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFree(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef PointerVal);
	Llvm34Library.LLVMValueRef LLVMBuildLoad(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef PointerVal, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildStore(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMValueRef Ptr);
	Llvm34Library.LLVMValueRef LLVMBuildGEP(Llvm34Library.LLVMBuilderRef B, Llvm34Library.LLVMValueRef Pointer, PointerByReference Indices, int NumIndices, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildGEP(Pointer B, Pointer Pointer, PointerByReference Indices, int NumIndices, Pointer Name);
	Llvm34Library.LLVMValueRef LLVMBuildInBoundsGEP(Llvm34Library.LLVMBuilderRef B, Llvm34Library.LLVMValueRef Pointer, PointerByReference Indices, int NumIndices, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildInBoundsGEP(Pointer B, Pointer Pointer, PointerByReference Indices, int NumIndices, Pointer Name);
	Llvm34Library.LLVMValueRef LLVMBuildStructGEP(Llvm34Library.LLVMBuilderRef B, Llvm34Library.LLVMValueRef Pointer, int Idx, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildGlobalString(Llvm34Library.LLVMBuilderRef B, String Str, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildGlobalStringPtr(Llvm34Library.LLVMBuilderRef B, String Str, String Name);
	int LLVMGetVolatile(Llvm34Library.LLVMValueRef MemoryAccessInst);
	void LLVMSetVolatile(Llvm34Library.LLVMValueRef MemoryAccessInst, int IsVolatile);
	Llvm34Library.LLVMValueRef LLVMBuildTrunc(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildZExt(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildSExt(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFPToUI(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFPToSI(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildUIToFP(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildSIToFP(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFPTrunc(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFPExt(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildPtrToInt(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildIntToPtr(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildBitCast(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildAddrSpaceCast(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildZExtOrBitCast(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildSExtOrBitCast(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildTruncOrBitCast(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildCast(Llvm34Library.LLVMBuilderRef B, int Op, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildPointerCast(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildIntCast(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFPCast(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, Llvm34Library.LLVMTypeRef DestTy, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildICmp(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, int Op, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildFCmp(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, int Op, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildPhi(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMTypeRef Ty, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildCall(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Fn, PointerByReference Args, int NumArgs, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildCall(Pointer LLVMBuilderRef1, Pointer Fn, PointerByReference Args, int NumArgs, Pointer Name);
	Llvm34Library.LLVMValueRef LLVMBuildSelect(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef If, Llvm34Library.LLVMValueRef Then, Llvm34Library.LLVMValueRef Else, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildVAArg(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef List, Llvm34Library.LLVMTypeRef Ty, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildExtractElement(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef VecVal, Llvm34Library.LLVMValueRef Index, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildInsertElement(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef VecVal, Llvm34Library.LLVMValueRef EltVal, Llvm34Library.LLVMValueRef Index, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildShuffleVector(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef V1, Llvm34Library.LLVMValueRef V2, Llvm34Library.LLVMValueRef Mask, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildExtractValue(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef AggVal, int Index, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildInsertValue(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef AggVal, Llvm34Library.LLVMValueRef EltVal, int Index, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildIsNull(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildIsNotNull(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef Val, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildPtrDiff(Llvm34Library.LLVMBuilderRef LLVMBuilderRef1, Llvm34Library.LLVMValueRef LHS, Llvm34Library.LLVMValueRef RHS, String Name);
	Llvm34Library.LLVMValueRef LLVMBuildAtomicRMW(Llvm34Library.LLVMBuilderRef B, int op, Llvm34Library.LLVMValueRef PTR, Llvm34Library.LLVMValueRef Val, int ordering, int singleThread);
	Llvm34Library.LLVMModuleProviderRef LLVMCreateModuleProviderForExistingModule(Llvm34Library.LLVMModuleRef M);
	void LLVMDisposeModuleProvider(Llvm34Library.LLVMModuleProviderRef M);
	int LLVMCreateMemoryBufferWithContentsOfFile(String Path, PointerByReference OutMemBuf, PointerByReference OutMessage);
	int LLVMCreateMemoryBufferWithContentsOfFile(Pointer Path, PointerByReference OutMemBuf, PointerByReference OutMessage);
	int LLVMCreateMemoryBufferWithSTDIN(PointerByReference OutMemBuf, PointerByReference OutMessage);
	Llvm34Library.LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRange(String InputData, NativeSize InputDataLength, String BufferName, int RequiresNullTerminator);
	Llvm34Library.LLVMMemoryBufferRef LLVMCreateMemoryBufferWithMemoryRangeCopy(String InputData, NativeSize InputDataLength, String BufferName);
	String LLVMGetBufferStart(Llvm34Library.LLVMMemoryBufferRef MemBuf);
	NativeSize LLVMGetBufferSize(Llvm34Library.LLVMMemoryBufferRef MemBuf);
	void LLVMDisposeMemoryBuffer(Llvm34Library.LLVMMemoryBufferRef MemBuf);
	Llvm34Library.LLVMPassRegistryRef LLVMGetGlobalPassRegistry();
	Llvm34Library.LLVMPassManagerRef LLVMCreatePassManager();
	Llvm34Library.LLVMPassManagerRef LLVMCreateFunctionPassManagerForModule(Llvm34Library.LLVMModuleRef M);
	Llvm34Library.LLVMPassManagerRef LLVMCreateFunctionPassManager(Llvm34Library.LLVMModuleProviderRef MP);
	int LLVMRunPassManager(Llvm34Library.LLVMPassManagerRef PM, Llvm34Library.LLVMModuleRef M);
	int LLVMInitializeFunctionPassManager(Llvm34Library.LLVMPassManagerRef FPM);
	int LLVMRunFunctionPassManager(Llvm34Library.LLVMPassManagerRef FPM, Llvm34Library.LLVMValueRef F);
	int LLVMFinalizeFunctionPassManager(Llvm34Library.LLVMPassManagerRef FPM);
	void LLVMDisposePassManager(Llvm34Library.LLVMPassManagerRef PM);
	int LLVMStartMultithreaded();
	void LLVMStopMultithreaded();
	int LLVMIsMultithreaded();
	Pointer lto_get_version();
	Pointer lto_get_error_message();
	byte lto_module_is_object_file(String path);
	byte lto_module_is_object_file_for_target(String path, String target_triple_prefix);
	byte lto_module_is_object_file_in_memory(Pointer mem, NativeSize length);
	byte lto_module_is_object_file_in_memory_for_target(Pointer mem, NativeSize length, String target_triple_prefix);
	Llvm34Library.lto_module_t lto_module_create(String path);
	Llvm34Library.lto_module_t lto_module_create_from_memory(Pointer mem, NativeSize length);
	Llvm34Library.lto_module_t lto_module_create_from_fd(int fd, String path, NativeSize file_size);
	Llvm34Library.lto_module_t lto_module_create_from_fd_at_offset(int fd, String path, NativeSize file_size, NativeSize map_size, long offset);
	void lto_module_dispose(Llvm34Library.lto_module_t mod);
	Pointer lto_module_get_target_triple(Llvm34Library.lto_module_t mod);
	void lto_module_set_target_triple(Llvm34Library.lto_module_t mod, String triple);
	int lto_module_get_num_symbols(Llvm34Library.lto_module_t mod);
	Pointer lto_module_get_symbol_name(Llvm34Library.lto_module_t mod, int index);
	int lto_module_get_symbol_attribute(Llvm34Library.lto_module_t mod, int index);
	Llvm34Library.lto_code_gen_t lto_codegen_create();
	void lto_codegen_dispose(Llvm34Library.lto_code_gen_t lto_code_gen_t1);
	byte lto_codegen_add_module(Llvm34Library.lto_code_gen_t cg, Llvm34Library.lto_module_t mod);
	byte lto_codegen_set_debug_model(Llvm34Library.lto_code_gen_t cg, int lto_debug_model1);
	byte lto_codegen_set_pic_model(Llvm34Library.lto_code_gen_t cg, int lto_codegen_model1);
	void lto_codegen_set_cpu(Llvm34Library.lto_code_gen_t cg, String cpu);
	void lto_codegen_set_assembler_path(Llvm34Library.lto_code_gen_t cg, String path);
	void lto_codegen_set_assembler_args(Llvm34Library.lto_code_gen_t cg, String args[], int nargs);
	void lto_codegen_add_must_preserve_symbol(Llvm34Library.lto_code_gen_t cg, String symbol);
	byte lto_codegen_write_merged_modules(Llvm34Library.lto_code_gen_t cg, String path);
	Pointer lto_codegen_compile(Llvm34Library.lto_code_gen_t cg, NativeSizeByReference length);
	byte lto_codegen_compile_to_file(Llvm34Library.lto_code_gen_t cg, String name[]);
	void lto_codegen_debug_options(Llvm34Library.lto_code_gen_t cg, String charPtr1);
	void lto_initialize_disassembler();
	int LLVMParseBitcode(Llvm34Library.LLVMMemoryBufferRef MemBuf, PointerByReference OutModule, PointerByReference OutMessage);
	int LLVMParseBitcode(Pointer MemBuf, PointerByReference OutModule, PointerByReference OutMessage);
	int LLVMParseBitcodeInContext(Llvm34Library.LLVMContextRef ContextRef, Llvm34Library.LLVMMemoryBufferRef MemBuf, PointerByReference OutModule, PointerByReference OutMessage);
	int LLVMParseBitcodeInContext(Pointer ContextRef, Pointer MemBuf, PointerByReference OutModule, PointerByReference OutMessage);
	int LLVMGetBitcodeModuleInContext(Llvm34Library.LLVMContextRef ContextRef, Llvm34Library.LLVMMemoryBufferRef MemBuf, PointerByReference OutM, PointerByReference OutMessage);
	int LLVMGetBitcodeModuleInContext(Pointer ContextRef, Pointer MemBuf, PointerByReference OutM, PointerByReference OutMessage);
	int LLVMGetBitcodeModule(Llvm34Library.LLVMMemoryBufferRef MemBuf, PointerByReference OutM, PointerByReference OutMessage);
	int LLVMGetBitcodeModule(Pointer MemBuf, PointerByReference OutM, PointerByReference OutMessage);
	int LLVMGetBitcodeModuleProviderInContext(Llvm34Library.LLVMContextRef ContextRef, Llvm34Library.LLVMMemoryBufferRef MemBuf, PointerByReference OutMP, PointerByReference OutMessage);
	int LLVMGetBitcodeModuleProviderInContext(Pointer ContextRef, Pointer MemBuf, PointerByReference OutMP, PointerByReference OutMessage);
	int LLVMGetBitcodeModuleProvider(Llvm34Library.LLVMMemoryBufferRef MemBuf, PointerByReference OutMP, PointerByReference OutMessage);
	int LLVMGetBitcodeModuleProvider(Pointer MemBuf, PointerByReference OutMP, PointerByReference OutMessage);
	int LLVMLoadLibraryPermanently(String Filename);
	int LLVMParseIRInContext(Llvm34Library.LLVMContextRef ContextRef, Llvm34Library.LLVMMemoryBufferRef MemBuf, PointerByReference OutM, PointerByReference OutMessage);
	int LLVMParseIRInContext(Pointer ContextRef, Pointer MemBuf, PointerByReference OutM, PointerByReference OutMessage);
	void LLVMLinkInJIT();
	void LLVMLinkInMCJIT();
	void LLVMLinkInInterpreter();
	Llvm34Library.LLVMGenericValueRef LLVMCreateGenericValueOfInt(Llvm34Library.LLVMTypeRef Ty, long N, int IsSigned);
	Llvm34Library.LLVMGenericValueRef LLVMCreateGenericValueOfPointer(Pointer P);
	Llvm34Library.LLVMGenericValueRef LLVMCreateGenericValueOfFloat(Llvm34Library.LLVMTypeRef Ty, double N);
	int LLVMGenericValueIntWidth(Llvm34Library.LLVMGenericValueRef GenValRef);
	long LLVMGenericValueToInt(Llvm34Library.LLVMGenericValueRef GenVal, int IsSigned);
	Pointer LLVMGenericValueToPointer(Llvm34Library.LLVMGenericValueRef GenVal);
	double LLVMGenericValueToFloat(Llvm34Library.LLVMTypeRef TyRef, Llvm34Library.LLVMGenericValueRef GenVal);
	void LLVMDisposeGenericValue(Llvm34Library.LLVMGenericValueRef GenVal);
	int LLVMCreateExecutionEngineForModule(PointerByReference OutEE, Llvm34Library.LLVMModuleRef M, PointerByReference OutError);
	int LLVMCreateExecutionEngineForModule(PointerByReference OutEE, Pointer M, PointerByReference OutError);
	int LLVMCreateInterpreterForModule(PointerByReference OutInterp, Llvm34Library.LLVMModuleRef M, PointerByReference OutError);
	int LLVMCreateInterpreterForModule(PointerByReference OutInterp, Pointer M, PointerByReference OutError);
	int LLVMCreateJITCompilerForModule(PointerByReference OutJIT, Llvm34Library.LLVMModuleRef M, int OptLevel, PointerByReference OutError);
	int LLVMCreateJITCompilerForModule(PointerByReference OutJIT, Pointer M, int OptLevel, PointerByReference OutError);
	void LLVMInitializeMCJITCompilerOptions(LLVMMCJITCompilerOptions Options, NativeSize SizeOfOptions);
	int LLVMCreateMCJITCompilerForModule(PointerByReference OutJIT, Llvm34Library.LLVMModuleRef M, LLVMMCJITCompilerOptions Options, NativeSize SizeOfOptions, PointerByReference OutError);
	int LLVMCreateMCJITCompilerForModule(PointerByReference OutJIT, Pointer M, LLVMMCJITCompilerOptions Options, NativeSize SizeOfOptions, PointerByReference OutError);
	int LLVMCreateExecutionEngine(PointerByReference OutEE, Llvm34Library.LLVMModuleProviderRef MP, PointerByReference OutError);
	int LLVMCreateExecutionEngine(PointerByReference OutEE, Pointer MP, PointerByReference OutError);
	int LLVMCreateInterpreter(PointerByReference OutInterp, Llvm34Library.LLVMModuleProviderRef MP, PointerByReference OutError);
	int LLVMCreateInterpreter(PointerByReference OutInterp, Pointer MP, PointerByReference OutError);
	int LLVMCreateJITCompiler(PointerByReference OutJIT, Llvm34Library.LLVMModuleProviderRef MP, int OptLevel, PointerByReference OutError);
	int LLVMCreateJITCompiler(PointerByReference OutJIT, Pointer MP, int OptLevel, PointerByReference OutError);
	void LLVMDisposeExecutionEngine(Llvm34Library.LLVMExecutionEngineRef EE);
	void LLVMRunStaticConstructors(Llvm34Library.LLVMExecutionEngineRef EE);
	void LLVMRunStaticDestructors(Llvm34Library.LLVMExecutionEngineRef EE);
	int LLVMRunFunctionAsMain(Llvm34Library.LLVMExecutionEngineRef EE, Llvm34Library.LLVMValueRef F, int ArgC, byte[] ArgV[], byte[] EnvP[]);
	Llvm34Library.LLVMGenericValueRef LLVMRunFunction(Llvm34Library.LLVMExecutionEngineRef EE, Llvm34Library.LLVMValueRef F, int NumArgs, PointerByReference Args);
	Llvm34Library.LLVMGenericValueRef LLVMRunFunction(Pointer EE, Pointer F, int NumArgs, PointerByReference Args);
	void LLVMFreeMachineCodeForFunction(Llvm34Library.LLVMExecutionEngineRef EE, Llvm34Library.LLVMValueRef F);
	void LLVMAddModule(Llvm34Library.LLVMExecutionEngineRef EE, Llvm34Library.LLVMModuleRef M);
	void LLVMAddModuleProvider(Llvm34Library.LLVMExecutionEngineRef EE, Llvm34Library.LLVMModuleProviderRef MP);
	int LLVMRemoveModule(Llvm34Library.LLVMExecutionEngineRef EE, Llvm34Library.LLVMModuleRef M, PointerByReference OutMod, PointerByReference OutError);
	int LLVMRemoveModule(Pointer EE, Pointer M, PointerByReference OutMod, PointerByReference OutError);
	int LLVMRemoveModuleProvider(Llvm34Library.LLVMExecutionEngineRef EE, Llvm34Library.LLVMModuleProviderRef MP, PointerByReference OutMod, PointerByReference OutError);
	int LLVMRemoveModuleProvider(Pointer EE, Pointer MP, PointerByReference OutMod, PointerByReference OutError);
	int LLVMFindFunction(Llvm34Library.LLVMExecutionEngineRef EE, String Name, PointerByReference OutFn);
	int LLVMFindFunction(Pointer EE, Pointer Name, PointerByReference OutFn);
	Pointer LLVMRecompileAndRelinkFunction(Llvm34Library.LLVMExecutionEngineRef EE, Llvm34Library.LLVMValueRef Fn);
	Llvm34Library.LLVMTargetDataRef LLVMGetExecutionEngineTargetData(Llvm34Library.LLVMExecutionEngineRef EE);
	void LLVMAddGlobalMapping(Llvm34Library.LLVMExecutionEngineRef EE, Llvm34Library.LLVMValueRef Global, Pointer Addr);
	Pointer LLVMGetPointerToGlobal(Llvm34Library.LLVMExecutionEngineRef EE, Llvm34Library.LLVMValueRef Global);
	Llvm34Library.LLVMMCJITMemoryManagerRef LLVMCreateSimpleMCJITMemoryManager(Pointer Opaque, Llvm34Library.LLVMMemoryManagerAllocateCodeSectionCallback AllocateCodeSection, Llvm34Library.LLVMMemoryManagerAllocateDataSectionCallback AllocateDataSection, Llvm34Library.LLVMMemoryManagerFinalizeMemoryCallback FinalizeMemory, Llvm34Library.LLVMMemoryManagerDestroyCallback Destroy);
	void LLVMDisposeMCJITMemoryManager(Llvm34Library.LLVMMCJITMemoryManagerRef MM);
	Pointer LLVMCreateDisasm(String TripleName, Pointer DisInfo, int TagType, Llvm34Library.LLVMOpInfoCallback GetOpInfo, Llvm34Library.LLVMSymbolLookupCallback SymbolLookUp);
	Pointer LLVMCreateDisasmCPU(String Triple, String CPU, Pointer DisInfo, int TagType, Llvm34Library.LLVMOpInfoCallback GetOpInfo, Llvm34Library.LLVMSymbolLookupCallback SymbolLookUp);
	int LLVMSetDisasmOptions(Pointer DC, long Options);
	void LLVMDisasmDispose(Pointer DC);
	NativeSize LLVMDisasmInstruction(Pointer DC, ByteBuffer Bytes, long BytesSize, long PC, ByteBuffer OutString, NativeSize OutStringSize);
	Llvm34Library.LLVMObjectFileRef LLVMCreateObjectFile(Llvm34Library.LLVMMemoryBufferRef MemBuf);
	void LLVMDisposeObjectFile(Llvm34Library.LLVMObjectFileRef ObjectFile);
	Llvm34Library.LLVMSectionIteratorRef LLVMGetSections(Llvm34Library.LLVMObjectFileRef ObjectFile);
	void LLVMDisposeSectionIterator(Llvm34Library.LLVMSectionIteratorRef SI);
	int LLVMIsSectionIteratorAtEnd(Llvm34Library.LLVMObjectFileRef ObjectFile, Llvm34Library.LLVMSectionIteratorRef SI);
	void LLVMMoveToNextSection(Llvm34Library.LLVMSectionIteratorRef SI);
	void LLVMMoveToContainingSection(Llvm34Library.LLVMSectionIteratorRef Sect, Llvm34Library.LLVMSymbolIteratorRef Sym);
	Llvm34Library.LLVMSymbolIteratorRef LLVMGetSymbols(Llvm34Library.LLVMObjectFileRef ObjectFile);
	void LLVMDisposeSymbolIterator(Llvm34Library.LLVMSymbolIteratorRef SI);
	int LLVMIsSymbolIteratorAtEnd(Llvm34Library.LLVMObjectFileRef ObjectFile, Llvm34Library.LLVMSymbolIteratorRef SI);
	void LLVMMoveToNextSymbol(Llvm34Library.LLVMSymbolIteratorRef SI);
	String LLVMGetSectionName(Llvm34Library.LLVMSectionIteratorRef SI);
	long LLVMGetSectionSize(Llvm34Library.LLVMSectionIteratorRef SI);
	String LLVMGetSectionContents(Llvm34Library.LLVMSectionIteratorRef SI);
	long LLVMGetSectionAddress(Llvm34Library.LLVMSectionIteratorRef SI);
	int LLVMGetSectionContainsSymbol(Llvm34Library.LLVMSectionIteratorRef SI, Llvm34Library.LLVMSymbolIteratorRef Sym);
	Llvm34Library.LLVMRelocationIteratorRef LLVMGetRelocations(Llvm34Library.LLVMSectionIteratorRef Section);
	void LLVMDisposeRelocationIterator(Llvm34Library.LLVMRelocationIteratorRef RI);
	int LLVMIsRelocationIteratorAtEnd(Llvm34Library.LLVMSectionIteratorRef Section, Llvm34Library.LLVMRelocationIteratorRef RI);
	void LLVMMoveToNextRelocation(Llvm34Library.LLVMRelocationIteratorRef RI);
	String LLVMGetSymbolName(Llvm34Library.LLVMSymbolIteratorRef SI);
	long LLVMGetSymbolAddress(Llvm34Library.LLVMSymbolIteratorRef SI);
	long LLVMGetSymbolFileOffset(Llvm34Library.LLVMSymbolIteratorRef SI);
	long LLVMGetSymbolSize(Llvm34Library.LLVMSymbolIteratorRef SI);
	long LLVMGetRelocationAddress(Llvm34Library.LLVMRelocationIteratorRef RI);
	long LLVMGetRelocationOffset(Llvm34Library.LLVMRelocationIteratorRef RI);
	Llvm34Library.LLVMSymbolIteratorRef LLVMGetRelocationSymbol(Llvm34Library.LLVMRelocationIteratorRef RI);
	long LLVMGetRelocationType(Llvm34Library.LLVMRelocationIteratorRef RI);
	String LLVMGetRelocationTypeName(Llvm34Library.LLVMRelocationIteratorRef RI);
	String LLVMGetRelocationValueString(Llvm34Library.LLVMRelocationIteratorRef RI);
	void LLVMInitializeTransformUtils(Llvm34Library.LLVMPassRegistryRef R);
	void LLVMInitializeScalarOpts(Llvm34Library.LLVMPassRegistryRef R);
	void LLVMInitializeObjCARCOpts(Llvm34Library.LLVMPassRegistryRef R);
	void LLVMInitializeVectorization(Llvm34Library.LLVMPassRegistryRef R);
	void LLVMInitializeInstCombine(Llvm34Library.LLVMPassRegistryRef R);
	void LLVMInitializeIPO(Llvm34Library.LLVMPassRegistryRef R);
	void LLVMInitializeInstrumentation(Llvm34Library.LLVMPassRegistryRef R);
	void LLVMInitializeAnalysis(Llvm34Library.LLVMPassRegistryRef R);
	void LLVMInitializeIPA(Llvm34Library.LLVMPassRegistryRef R);
	void LLVMInitializeCodeGen(Llvm34Library.LLVMPassRegistryRef R);
	void LLVMInitializeTarget(Llvm34Library.LLVMPassRegistryRef R);
	/** Pointer to unknown (opaque) type */
	public static class LLVMObjectFileRef extends PointerType {
		public LLVMObjectFileRef(Pointer address) {
			super(address);
		}
		public LLVMObjectFileRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMValueRef extends PointerType {
		public LLVMValueRef(Pointer address) {
			super(address);
		}
		public LLVMValueRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMTypeRef extends PointerType {
		public LLVMTypeRef(Pointer address) {
			super(address);
		}
		public LLVMTypeRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMModuleProviderRef extends PointerType {
		public LLVMModuleProviderRef(Pointer address) {
			super(address);
		}
		public LLVMModuleProviderRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMBasicBlockRef extends PointerType {
		public LLVMBasicBlockRef(Pointer address) {
			super(address);
		}
		public LLVMBasicBlockRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMPassRegistryRef extends PointerType {
		public LLVMPassRegistryRef(Pointer address) {
			super(address);
		}
		public LLVMPassRegistryRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMTargetDataRef extends PointerType {
		public LLVMTargetDataRef(Pointer address) {
			super(address);
		}
		public LLVMTargetDataRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMBuilderRef extends PointerType {
		public LLVMBuilderRef(Pointer address) {
			super(address);
		}
		public LLVMBuilderRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class lto_code_gen_t extends PointerType {
		public lto_code_gen_t(Pointer address) {
			super(address);
		}
		public lto_code_gen_t() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMContextRef extends PointerType {
		public LLVMContextRef(Pointer address) {
			super(address);
		}
		public LLVMContextRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMSymbolIteratorRef extends PointerType {
		public LLVMSymbolIteratorRef(Pointer address) {
			super(address);
		}
		public LLVMSymbolIteratorRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMTargetRef extends PointerType {
		public LLVMTargetRef(Pointer address) {
			super(address);
		}
		public LLVMTargetRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMPassManagerRef extends PointerType {
		public LLVMPassManagerRef(Pointer address) {
			super(address);
		}
		public LLVMPassManagerRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMRelocationIteratorRef extends PointerType {
		public LLVMRelocationIteratorRef(Pointer address) {
			super(address);
		}
		public LLVMRelocationIteratorRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMTargetMachineRef extends PointerType {
		public LLVMTargetMachineRef(Pointer address) {
			super(address);
		}
		public LLVMTargetMachineRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMModuleRef extends PointerType {
		public LLVMModuleRef(Pointer address) {
			super(address);
		}
		public LLVMModuleRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMGenericValueRef extends PointerType {
		public LLVMGenericValueRef(Pointer address) {
			super(address);
		}
		public LLVMGenericValueRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMUseRef extends PointerType {
		public LLVMUseRef(Pointer address) {
			super(address);
		}
		public LLVMUseRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMPassManagerBuilderRef extends PointerType {
		public LLVMPassManagerBuilderRef(Pointer address) {
			super(address);
		}
		public LLVMPassManagerBuilderRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class lto_module_t extends PointerType {
		public lto_module_t(Pointer address) {
			super(address);
		}
		public lto_module_t() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMExecutionEngineRef extends PointerType {
		public LLVMExecutionEngineRef(Pointer address) {
			super(address);
		}
		public LLVMExecutionEngineRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMTargetLibraryInfoRef extends PointerType {
		public LLVMTargetLibraryInfoRef(Pointer address) {
			super(address);
		}
		public LLVMTargetLibraryInfoRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMMemoryBufferRef extends PointerType {
		public LLVMMemoryBufferRef(Pointer address) {
			super(address);
		}
		public LLVMMemoryBufferRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMSectionIteratorRef extends PointerType {
		public LLVMSectionIteratorRef(Pointer address) {
			super(address);
		}
		public LLVMSectionIteratorRef() {
			super();
		}
	};
	/** Pointer to unknown (opaque) type */
	public static class LLVMMCJITMemoryManagerRef extends PointerType {
		public LLVMMCJITMemoryManagerRef(Pointer address) {
			super(address);
		}
		public LLVMMCJITMemoryManagerRef() {
			super();
		}
	};
}