package llvm;
import com.ochafik.lang.jnaerator.runtime.Structure;
import com.sun.jna.Pointer;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class LLVMOpInfoSymbol1 extends Structure<LLVMOpInfoSymbol1, LLVMOpInfoSymbol1.ByValue, LLVMOpInfoSymbol1.ByReference > {
	/** 1 if this symbol is present */
	public long Present;
	/** symbol name if not NULL */
	public Pointer Name;
	/** symbol value if name is NULL */
	public long Value;
	public LLVMOpInfoSymbol1() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("Present", "Name", "Value");
	}
	public LLVMOpInfoSymbol1(long Present, Pointer Name, long Value) {
		super();
		this.Present = Present;
		this.Name = Name;
		this.Value = Value;
	}
	public LLVMOpInfoSymbol1(Pointer peer) {
		super(peer);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected LLVMOpInfoSymbol1 newInstance() { return new LLVMOpInfoSymbol1(); }
	public static LLVMOpInfoSymbol1[] newArray(int arrayLength) {
		return Structure.newArray(LLVMOpInfoSymbol1.class, arrayLength);
	}
	public static class ByReference extends LLVMOpInfoSymbol1 implements Structure.ByReference {
		
	};
	public static class ByValue extends LLVMOpInfoSymbol1 implements Structure.ByValue {
		
	};
}
